bluetooth deprecate old params
lasers/py3status pull request #1
Opened 2017-03-19 15:21 UTC by tobes

I think this should fix the deprecation stuff.

It is a bit horrible but should ensure nice backwards compatibility for all the old format options.

It is a shame it is so much code though.

2017-03-29 09:24 UTC, tobes commented
ping

2017-03-29 19:18 UTC, lasers requested changes

2017-03-29 19:18 UTC, lasers commented on py3status/modules/bluetooth.py
> +DEFAULT_FORMAT = 'BT: [{format_device}|\?show OFF]'
Can we change this to `BT[: {format_device}]`? It shouldn't affect users with existing config.

2017-03-29 23:52 UTC, tobes commented on py3status/modules/bluetooth.py
> +DEFAULT_FORMAT = 'BT: [{format_device}|\?show OFF]'
you drive a hard bargain

2017-03-30 06:13 UTC, lasers approved these changes

2017-03-30 06:14 UTC, merged

2017-03-30 11:50 UTC, lasers commented
@tobes Good work putting everything together. I see what you did with `get_placeholders_list` there. This should work okay with the sorted list...

Although there may be no good usecase for where people actually would want to put in repeated placeholders, we should still pass them along too to keep things consistent. I just hope that day never come. You get a medal for this. Thank you. 🥇